export let facts=[
    {"num":"1","fact":"11% of people are left handed" },
    {"num":"2","fact":"August has the highest percentage of births" },
    {"num":"3","fact":"unless food is mixed with saliva you can't taste it" },
    {"num":"4","fact":"the average person falls asleep in 7 minutes" },
    {"num":"5","fact":"a bear has 42 teeth" },
    {"num":"6","fact":"an ostrich's eye is bigger than its brain" },
    {"num":"7","fact":"lemons contain more sugar than strawberries" },
    {"num":"8","fact":"8% of people have an extra rib" },
    {"num":"9","fact":"a lobsters blood is colorless but when exposed to oxygen it turns blue" },
    {"num":"10","fact":"reindeer like bananas" },
    {"num":"11","fact":"the most commonly used letter in the alphabet is E" },
    {"num":"12","fact":"the smallest bones in the human body are found in your ear" },
    {"num":"13","fact":"Switzerland eats the most chocolate equating to 10 kilos per person per year" },
    {"num":"14","fact":"money is the number one thing that couples argue about" },
    {"num":"15","fact":"each time you see a full moon you always see the same side" },
    {"num":"16","fact":"honey is the only natural food which never spoils" },
    {"num":"17","fact":"that you burn more calories eating celery than it contains (the more you eat the thinner you become)" },
    {"num":"18","fact":"the longest street in the world is Yonge street in Toronto Canada measuring 1,896 km (1,178 miles)" },
    {"num":"19","fact":"Coca-Cola originally contained cocaine" },
    {"num":"20","fact":"the Internet was originally called ARPANet (Advanced Research Projects Agency Network) designed by the US department of defense" },
    {"num":"21","fact":"In eastern Africa you can buy beer brewed from bananas" },
    {"num":"22","fact":"on your birthday you share it with 9 million others" },
    {"num":"23","fact":"in 1878 the first telephone book made contained only 50 names" },
    {"num":"24","fact":"everyday is a holiday somewhere in the world" },
    {"num":"25","fact":"french fries are originally from Belgium" },
    {"num":"26","fact":"in a deck of cards the king of hearts is the only king without a moustache" },
    {"num":"27","fact":"'Bookkeeper' and 'bookkeeping' are the only 2 words in the English language with three consecutive double letters" },
    {"num":"28","fact":"the dot on top of the letter 'i' is called a tittle" },
    {"num":"29","fact":"you're more likely to be killed by a champagne cork than by a poisonous spider" },
    {"num":"30","fact":"women blink twice as much as men" },
    {"num":"31","fact":"India has the most post offices than any other country (over 100,000)" },
    {"num":"32","fact":"every single possible 3 character .com domain has been registered" },
    {"num":"33","fact":"the word 'uncopyrightable' is the is the only 15 letter word that can be spelled without repeating any letter" },
    {"num":"34","fact":"the word 'testify' derived from a time when men were required to swear on their testicles" },
    {"num":"35","fact":"an egg contains every vitamin except vitamin C" },
    {"num":"36","fact":"a piece of paper cannot be folded more than 7 times" },
    {"num":"37","fact":"Buckingham Palace has over 600 rooms" },
    {"num":"38","fact":"you burn more calories sleeping than watching television" },
    {"num":"39","fact":"the rarest type of diamond is green" },
    {"num":"40","fact":"wine is sold in tinted bottles because it spoils when exposed to light" },
    {"num":"41","fact":"the odds of being struck by lightning are 600,000 to 1" },
    {"num":"42","fact":"the first train reached a top speed of only 8 kmh (5 mph)" },
    {"num":"43","fact":"ice skating rinks always go counter clock wise (for the majority of people that are right handed needing to hang onto the rail)" },
    {"num":"44","fact":"the world's knowledge is growing so fast that 90% of what we will know in 50 years time will be discovered in those 50 years" },
    {"num":"45","fact":"paper money was first used in China" },
    {"num":"46","fact":"most of the Vitamin C found in fruits is in the skin" },
    {"num":"47","fact":"everyday, more money is printed for Monopoly sets than for the U.S. Treasury" },
    {"num":"48","fact":"coconuts kill over 150 people each year (more than sharks)" },
    {"num":"49","fact":"employees are more likely to book holidays off work on a Monday that any other week day" },
    {"num":"50","fact":"most cows produce more milk when they listen to music" }
    ];
